# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NewDash.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1901, 938)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/dashboard-5-48.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QMainWindow {\n"
"    background-color:#ececec;\n"
"}\n"
"QPushButton, QToolButton, QCommandLinkButton{\n"
"    padding: 0 5px 0 5px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0, y1:1, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    color: #616161;\n"
"    font-weight: bold;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #fbfdfd, stop:0.5 #ffffff, stop:1 #fbfdfd);\n"
"}\n"
"QPushButton::default, QToolButton::default, QCommandLinkButton::default{\n"
"    border: 2px solid transparent;\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QPushButton:hover, QToolButton:hover, QCommandLinkButton:hover{\n"
"    color: #3d3d3d;\n"
"}\n"
"QPushButton:pressed, QToolButton:pressed, QCommandLinkButton:pressed{\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QPushButton:disabled, QToolButton:disabled, QCommandLinkButton:disabled{\n"
"    color: #616161;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #dce7eb, stop:0.5 #e0e8eb, stop:1 #dee7ec);\n"
"}\n"
"QLineEdit, QTextEdit, QPlainTextEdit, QSpinBox, QDoubleSpinBox, QTimeEdit, QDateEdit, QDateTimeEdit {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:focus, QTextEdit:focus, QPlainTextEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus, QTimeEdit:focus, QDateEdit:focus, QDateTimeEdit:focus {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #85b7e3, stop:1 #9ec1db);\n"
"    background-color: #f4f4f4;\n"
"    color: #3d3d3d;\n"
"}\n"
"QLineEdit:disabled, QTextEdit:disabled, QPlainTextEdit:disabled, QSpinBox:disabled, QDoubleSpinBox:disabled, QTimeEdit:disabled, QDateEdit:disabled, QDateTimeEdit:disabled {\n"
"    color: #b9b9b9;\n"
"}\n"
"QSpinBox::up-button, QDoubleSpinBox::up-button, QTimeEdit::up-button, QDateEdit::up-button, QDateTimeEdit::up-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::down-button, QDoubleSpinBox::down-button, QTimeEdit::down-button, QDateEdit::down-button, QDateTimeEdit::down-button {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: bottom right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-bottom-right-radius: 3px;\n"
"    padding: 3px;\n"
"}\n"
"QSpinBox::up-button:pressed, QDoubleSpinBox::up-button:pressed, QTimeEdit::up-button:pressed, QDateEdit::up-button:pressed, QDateTimeEdit::up-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::down-button:pressed, QDoubleSpinBox::down-button:pressed, QTimeEdit::down-button:pressed, QDateEdit::down-button:pressed, QDateTimeEdit::down-button:pressed {\n"
"    color: #aeaeae;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #ffffff, stop:0.5 #fbfdfd, stop:1 #ffffff);\n"
"}\n"
"QSpinBox::up-button:hover, QDoubleSpinBox::up-button:hover, QTimeEdit::up-button:hover, QDateEdit::up-button:hover, QDateTimeEdit::up-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-top-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"    \n"
"}\n"
"QSpinBox::down-button:hover, QDoubleSpinBox::down-button:hover, QTimeEdit::down-button:hover, QDateEdit::down-button:hover, QDateTimeEdit::down-button:hover {\n"
"    color: #FFFFFF;\n"
"    border-bottom-right-radius: 5px;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QSpinBox::up-arrow, QDoubleSpinBox::up-arrow, QTimeEdit::up-arrow, QDateEdit::up-arrow, QDateTimeEdit::up-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QSpinBox::down-arrow, QDoubleSpinBox::down-arrow, QTimeEdit::down-arrow, QDateEdit::down-arrow, QDateTimeEdit::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QProgressBar {\n"
"    max-height: 8px;\n"
"    text-align: center;\n"
"    font: italic bold 11px;\n"
"    color: #3d3d3d;\n"
"    border: 1px solid transparent;\n"
"    border-radius:4px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QProgressBar::chunk {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"    border-radius: 4px;\n"
"}\n"
"QProgressBar:disabled {\n"
"    color: #616161;\n"
"}\n"
"QProgressBar::chunk:disabled {\n"
"    background-color: #aeaeae;\n"
"}\n"
"QSlider::groove {\n"
"    border: 1px solid #bbbbbb;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::groove:horizontal {\n"
"    height: 6px;\n"
"}\n"
"QSlider::groove:vertical {\n"
"    width: 6px;\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    width: 12px;\n"
"    margin: -5px 0;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background: #ffffff;\n"
"    border-style: solid;\n"
"    border-width: 1px;\n"
"    border-color: rgb(207,207,207);\n"
"    height: 12px;\n"
"    margin: 0 -5px;\n"
"    border-radius: 7px;\n"
"}\n"
"QSlider::add-page, QSlider::sub-page {\n"
"    border: 1px transparent;\n"
"    background-color: #52595d;\n"
"    border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::add-page:vertical {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #ddd5d5, stop:0.5 #dad3d3, stop:1 #ddd5d5);\n"
"}\n"
"QSlider::add-page:horizontal:disabled, QSlider::sub-page:horizontal:disabled, QSlider::add-page:vertical:disabled, QSlider::sub-page:vertical:disabled {\n"
"    background: #b9b9b9;\n"
"}\n"
"QComboBox, QFontComboBox {\n"
"    border-width: 2px;\n"
"    border-radius: 8px;\n"
"    border-style: solid;\n"
"    border-top-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-right-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-bottom-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    border-left-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:0, stop:0 #c1c9cf, stop:1 #d2d8dd);\n"
"    background-color: #f4f4f4;\n"
"    color: #272727;\n"
"    padding-left: 5px;\n"
"}\n"
"QComboBox:editable, QComboBox:!editable, QComboBox::drop-down:editable, QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"    background: #ffffff;\n"
"}\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"    color: #272727;\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid;\n"
"    border-top-right-radius: 3px;\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png); /*Adawaita icon thene*/\n"
"}\n"
"\n"
"QComboBox::down-arrow:on {\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    border: 1px solid darkgray;\n"
"    border-radius: 8px;\n"
"    selection-background-color: #dadada;\n"
"    selection-color: #272727;\n"
"    color: #272727;\n"
"    background: white;\n"
"}\n"
"QLabel, QCheckBox, QRadioButton {\n"
"    color: #272727;\n"
"}\n"
"QCheckBox {\n"
"    padding: 2px;\n"
"}\n"
"QCheckBox:disabled, QRadioButton:disabled {\n"
"    color: #808086;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QCheckBox:hover {\n"
"    border-radius:4px;\n"
"    border-style:solid;\n"
"    padding-left: 1px;\n"
"    padding-right: 1px;\n"
"    padding-bottom: 1px;\n"
"    padding-top: 1px;\n"
"    border-width:1px;\n"
"    border-color: transparent;\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/object-select-symbolic.symbolic.png);\n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    color: #ffffff;\n"
"    border-radius: 3px;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 #48a5fd, stop:0.5 #329cfb, stop:1 #48a5fd);\n"
"}\n"
"QCheckBox::indicator:unchecked {\n"
"    \n"
"    height: 15px;\n"
"    width: 15px;\n"
"    border-style:solid;\n"
"    border-width: 1px;\n"
"    border-color: #48a5fd;\n"
"    border-radius: 3px;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QLCDNumber {\n"
"    color: #616161;;\n"
"}\n"
"QMenuBar {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenuBar::item {\n"
"    color: #616161;\n"
"    spacing: 3px;\n"
"    padding: 1px 4px;\n"
"    background-color: #ececec;\n"
"}\n"
"\n"
"QMenuBar::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu {\n"
"    background-color: #ececec;\n"
"}\n"
"QMenu::item:selected {\n"
"    background-color: #dadada;\n"
"    color: #3d3d3d;\n"
"}\n"
"QMenu::item {\n"
"    color: #616161;;\n"
"    background-color: #e0e0e0;\n"
"}\n"
"QTabWidget {\n"
"    color:rgb(0,0,0);\n"
"    background-color:#000000;\n"
"}\n"
"QTabWidget::pane {\n"
"    border-color: #050a0e;\n"
"    background-color: #e0e0e0;\n"
"    border-width: 1px;\n"
"    border-radius: 4px;\n"
"    position: absolute;\n"
"    top: -0.5em;\n"
"    padding-top: 0.5em;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    border-bottom: 1px solid #c0c0c0;\n"
"    padding: 3px;\n"
"    color: #272727;\n"
"    background-color: #fefefc;\n"
"    margin-left:0px;\n"
"}\n"
"QTabBar::tab:!last {\n"
"    border-right: 1px solid;\n"
"    border-right-color: #c0c0c0;\n"
"    border-bottom-color: #c0c0c0;\n"
"}\n"
"QTabBar::tab:first {\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"}\n"
"QTabBar::tab:last {\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"}\n"
"QTabBar::tab:selected, QTabBar::tab:last:selected, QTabBar::tab:hover {\n"
"    color: #FFFFFF;\n"
"    background-color: qlineargradient(spread:pad, x1:0.5, y1:0, x2:0.5, y2:1, stop:0 #84afe5, stop:1 #1168e4);\n"
"}\n"
"QRadioButton::indicator {\n"
"    height: 14px;\n"
"    width: 14px;\n"
"    border-style:solid;\n"
"    border-radius:7px;\n"
"    border-width: 1px;\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    border-color: #48a5fd;\n"
"    background-color: qradialgradient(cx:0.5, cy:0.5, radius:0.4,fx:0.5, fy:0.5, stop:0 #ffffff, stop:0.5 #ffffff, stop:0.6 #48a5fd, stop:1 #48a5fd);\n"
"}\n"
"QRadioButton::indicator:!checked {\n"
"    border-color: #a9b7c6;\n"
"    background-color: #fbfdfa;\n"
"}\n"
"QStatusBar {\n"
"    color:#242626;\n"
"}\n"
"\n"
"QDial {\n"
"    background: #16a085;\n"
"}\n"
"\n"
"QToolBox {\n"
"    color: #a9b7c6;\n"
"    background-color: #222b2e;\n"
"}\n"
"QToolBox::tab {\n"
"    color: #a9b7c6;\n"
"    background-color:#222b2e;\n"
"}\n"
"QToolBox::tab:selected {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"QScrollArea {\n"
"    color: #FFFFFF;\n"
"    background-color:#222b2e;\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    max-height: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 0px 20px 0px 20px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar:vertical {\n"
"    max-width: 10px;\n"
"    border: 1px transparent grey;\n"
"    margin: 20px 0px 20px 0px;\n"
"    background: transparent;\n"
"}\n"
"QScrollBar::handle:vertical, QScrollBar::handle:horizontal {\n"
"    background: #52595d;\n"
"    border-style: transparent;\n"
"    border-radius: 4px;\n"
"    min-height: 25px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover, QScrollBar::handle:vertical:hover {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    border: 2px transparent grey;\n"
"    border-radius: 4px;\n"
"    subcontrol-origin: margin;\n"
"    background: #b9b9b9;\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: right;\n"
"}\n"
"QScrollBar::add-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: bottom;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    width: 20px;\n"
"    subcontrol-position: left;\n"
"}\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 20px;\n"
"    subcontrol-position: top;\n"
"}\n"
"QScrollBar::add-line:vertical:pressed, QScrollBar::add-line:horizontal:pressed, QScrollBar::sub-line:horizontal:pressed, QScrollBar::sub-line:vertical:pressed {\n"
"    background: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 #467dd1, stop:0.5 #3b88fc, stop:1 #467dd1);\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal, QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"QScrollBar::up-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-up-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::down-arrow:vertical {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-down-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::left-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-previous-symbolic.symbolic.png);\n"
"}\n"
"QScrollBar::right-arrow:horizontal {\n"
"    image: url(/usr/share/icons/Adwaita/16x16/actions/go-next-symbolic.symbolic.png);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(-10, 0, 1941, 931))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 128, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 128, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(249, 249, 249))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(67, 128, 179))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.NoBrush)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)
        self.tabWidget.setPalette(palette)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("/*  ---------------------------- ALL OTHERS WIDGETS ---------------------------- */\n"
"*{\n"
"selection-background-color: rgb(67, 128, 179);\n"
"selection-color: rgb(255, 255, 255);\n"
"font-family:Segoe UI;\n"
"}\n"
"\n"
"/*  ---------------------------- MAIN WINDOW, WIDGET ---------------------------- */\n"
"QMainWindow,QWidget\n"
"{\n"
"color:rgb(0,0,0);\n"
"background:rgb(255,255,255);\n"
"background-color:#F9F9F9;\n"
"}\n"
"\n"
"/*  ---------------------------- MENU BAR ---------------------------- */\n"
"QMenuBar\n"
"{\n"
"color:rgb(120,120,120);\n"
"background:rgb(230,230,230);\n"
"}\n"
"QMenuBar::item:selected\n"
"{\n"
"color:rgb(100,100,100);\n"
"background:rgb(200,200,200);\n"
"}\n"
"/*  ---------------------------- CONTEXT MENU ---------------------------- */\n"
"QMenu\n"
"{\n"
"color:rgb(90,90,90);\n"
"background:rgb(230,230,230);\n"
"padding: 3;\n"
"}\n"
"QMenu::item:selected\n"
"{\n"
"color:rgb(90,90,90);\n"
"background:rgb(200,200,200);\n"
"}\n"
"QMenu::separator {\n"
"background:rgb(200,200,200);\n"
"height:1px;\n"
"}\n"
"\n"
"\n"
"/*  ---------------------------- Q TAB BAR ---------------------------- */\n"
"QTabBar::tab {\n"
"color:rgb(150,150,150);\n"
"background:rgb(240,240,240);\n"
"height:30;\n"
"width:80;\n"
"border: rgb(240,240,240);\n"
"border-width: 0 0 2px 0;\n"
"padding-left:10;\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"background:white;\n"
"color:rgb(100,100,100);\n"
"border: solid rgb(0,150,255);\n"
"border-width: 0 0 5px 0;\n"
"}\n"
"QTableWidget QTableCornerButton::section {\n"
"background-color: rgb(255, 255, 255);\n"
"}\n"
"/*-----------------------------------------------------------------\n"
"------------------------------ LINE_EDIT --------------------------\n"
"------------------------------ TEXT BROWSER -----------------------\n"
"------------------------------ TEXT_EDIT---------------------------\n"
"------------------------------ PLAIN_TEXT -------------------------\n"
"------------------------------------------------------------------- */\n"
"QLineEdit,QTextBrowser,QTextEdit,QPlainTextEdit\n"
"{\n"
"\n"
"border-width: 1px; border-radius: 4px;\n"
"border-style: solid;\n"
"border-color: qlineargradient(spread:pad, x1:0.5, y1:1, x2:0.5, y2:0, stop:0 rgba(0, 113, 255, 255), stop:1 rgba(91, 171, 252, 255));\n"
"\n"
"/* color:rgb(20,20,20);\n"
"background-color:white;\n"
"border: solid lightgrey;\n"
"border-width: 0 0 2px 0;\n"
"border-bottom-left-radius: 5;\n"
"border-bottom-right-radius: 5; */\n"
"}\n"
"\n"
"QLineEdit:disabled\n"
"{\n"
"color:rgb(118, 115, 115);\n"
"background-color:rgb(255, 240, 240);\n"
"border: solid rgb(164, 164, 164);\n"
"border-width: 0 0 2px 0;\n"
"border-bottom-left-radius: 5;\n"
"border-bottom-right-radius: 5;\n"
"}\n"
"\n"
"/*  ---------------------------- COMBO BOX ----------------------------*/\n"
"QComboBox\n"
"{\n"
"color:rgb(0,115,170);\n"
"background-color:rgb(255, 255, 255);\n"
"min-width: 5px;\n"
"padding: 1px 0px 1px 3px;\n"
"border: 1px solid rgb(0,115,170);\n"
"}\n"
"\n"
"QComboBox:hover\n"
"{\n"
"color:rgb(0,115,170);\n"
"background-color: white;\n"
"}\n"
"\n"
"QComboBox:selected\n"
"{\n"
"color:rgb(0,115,170);\n"
"selection-background-color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QComboBox::drop-down\n"
"{\n"
"width: 30px;\n"
"background-color:rgb(0,115,170);\n"
"}\n"
"\n"
"QComboBox::down-arrow\n"
"{\n"
"width: 14px;\n"
"height: 14px;\n"
"}\n"
"\n"
"\n"
"/* -------------------------------- CHECK BOX ----------------------------------------- */\n"
"QCheckBox\n"
"{\n"
"background: #F9F9F9;\n"
"color:rgb(25, 29, 32);\n"
"padding: 6;\n"
"}\n"
"/* ----------------------------  TOOL BOX  ----------------------------  */\n"
"QToolBox::tab\n"
"{\n"
"color:darkgrey;\n"
"background:lightgrey;\n"
"}\n"
"QToolBox::tab::selected\n"
"{\n"
"color:grey;\n"
"background:rgb(250, 250,250);\n"
"}\n"
"QToolBox::tab::hover\n"
"{\n"
"color:white;\n"
"background:rgb(0,115,170);\n"
"}\n"
"/*  ---------------------------- PROGRESS BAR ---------------------------- */\n"
"QProgressBar {\n"
"color:grey;\n"
"text-align: center;\n"
"font-size:13px;\n"
"}\n"
"QProgressBar::chunk {\n"
"background:rgb(0, 193, 50);\n"
"}\n"
"/*  ---------------------------- PUSHBUTTON ---------------------------- */\n"
"QPushButton\n"
"{\n"
"border: 1px solid lightgrey;\n"
"color:white;\n"
"background:rgb(0,115,170);\n"
"min-height:30;\n"
"min-width: 50;\n"
"}\n"
"QPushButton:hover\n"
"{\n"
"border: 1px solid lightgrey;\n"
"color:white;\n"
"background:rgb(0, 120, 210);\n"
"}\n"
"\n"
"QPushButton:pressed\n"
"{\n"
"border: 1px solid lightgrey;\n"
"color:white;\n"
"background:rgb(0, 53, 100);\n"
"}\n"
"/*  ----------------------------  LCD NUMBER ---------------------------- */\n"
"QLCDNumber\n"
"{\n"
"color:rgb(0,115,170);\n"
"border:2 solid rgb(100,100,100);\n"
"}\n"
"/*  ---------------------------- TABLE_LIST_TABLE ---------------------------- */\n"
"QTableView,\n"
"QTableWidget\n"
"{\n"
"alternate-background-color: rgb(240, 250, 255);\n"
"}\n"
"QTreeView\n"
"{\n"
"background: rgb(250,250,250);\n"
"color: rgb(180,180,180);\n"
"}\n"
"QTableView::item:selected, \n"
"QListView::item:selected,\n"
"QTableView::item:hover, \n"
"QListView::item:hover, \n"
"QTreeView::item:hover\n"
"{\n"
"background:rgb(0,115,170);\n"
"color:rgb(250,250,250);\n"
"}\n"
"QTableView::item, \n"
"QListView::item, \n"
"QTreeView::item\n"
"{\n"
"color:rgb(100,100,100);\n"
"}\n"
"QTreeView::item:selected,QListView::item:selected,QTableView::item:selected\n"
"{\n"
"color:rgb(37, 62, 71);\n"
"background:rgb(209, 241, 252);\n"
"}\n"
"/* QTreeView::item:has-children\n"
"{\n"
"background-color: rgb(0, 78, 134);\n"
"color: white;\n"
"border-bottom: 2px solid qlineargradient(spread:pad, x1:1, y1:0.5, x2:0, y2:0.5, stop:0 rgba(255, 255, 255, 0), stop:0.5 rgba(0, 150, 255, 255), stop:1 rgba(255, 255, 255, 0));\n"
"}\n"
"*/\n"
"/*  ---------------------------- HEADER VIEW ---------------------------- */\n"
"QHeaderView::section\n"
"{\n"
"color:rgb(133, 133, 133);\n"
"background:white;\n"
"border:transparent;\n"
"text-align:center;\n"
"padding:1;\n"
"}\n"
"/* ------------------------------- CALENDAR -------------------------------------------------- */\n"
"QCalendarView\n"
"{\n"
"color: rgb(20,20,20);\n"
"background-color: rgb(240,240,240);\n"
"alternate-background-color: rgb(0,115,170);\n"
"selection-background-color: white;\n"
"selection-color: black;\n"
"}\n"
"QAbstractItemView\n"
"{\n"
"color:rgb(200,200,200);\n"
"}\n"
"\n"
"\n"
"/* ---------------------------------------- SLIDER HORIZONTAL ----------------------------------------------- */\n"
"\n"
"\n"
"QSlider::groove:horizontal,QSlider::add-page:horizontal\n"
"{\n"
"background: rgb(255, 255, 255);\n"
"height: 27px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"height: 10px;\n"
"background: rgb(0,115,170);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"margin-right: -10px;\n"
"margin-left: -10px;\n"
"background: rgb(0,115,170);\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"background:rgb(0,115,170);\n"
"}\n"
"\n"
"/* --------------------------------  VERTICAL SLIDER --------------------------------------------------------------  */\n"
"\n"
"QSlider::handle\n"
"{\n"
"border-radius: 3px;\n"
"}\n"
"\n"
"QSlider::groove:vertical,QSlider::add-page:vertical,QSlider::sub-page:vertical\n"
"{\n"
"width: 20px;\n"
"background: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QSlider::handle:vertical {\n"
"margin-top: -10px;\n"
"margin-bottom: -10px;\n"
"background: rgb(0,115,170);\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"background: rgb(0,115,170);\n"
"}\n"
"\n"
"/* --------------------------------- SCROLLBAR HORIZONTAL --------------------------------------  */\n"
"\n"
"QScrollBar::groove:horizontal{\n"
"background: white;\n"
"height: 17px;\n"
"}\n"
"QScrollBar::sub-page:horizontal,QScrollBar::add-page:horizontal  {\n"
"height: 10px;\n"
"background: rgb(255, 255, 255);\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"margin-right: -5px;\n"
"background: rgb(0,115,170);\n"
"}\n"
"QScrollBar::handle:horizontal:hover {\n"
"background: rgb(0,115,170);\n"
"}\n"
"\n"
"/* --------------------------------------- SCROLLBAR VERTICAL ----------------------------------------------  */\n"
"\n"
"/* SCROLLBAR */\n"
"QScrollBar:vertical {\n"
"background: white;\n"
"width: 15px;\n"
"margin: 22px 0 22px 0;\n"
"}\n"
"/* HANDLE*/\n"
"QScrollBar::handle:vertical {\n"
"background: rgb(0,115,170);\n"
"min-height: 20px;\n"
"}\n"
"\n"
"/* UP ARROW */\n"
"QScrollBar::up-arrow:vertical {\n"
"image: url(assets/UI/Icons/interface_icons/arrow_up.png);\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"/* DOWN ARROW */\n"
"QScrollBar::down-arrow:vertical {\n"
"image: url(assets/UI/Icons/interface_icons/arrow_down.png);\n"
"width: 10px;\n"
"height: 10px;\n"
"}\n"
"/* UP BUTTON */\n"
"QScrollBar::sub-line:vertical {\n"
"background: rgb(0,115,170);\n"
"height: 20px;\n"
"subcontrol-position: top;\n"
"subcontrol-origin: margin;\n"
"}\n"
"/* DOWN BUTTON */\n"
"QScrollBar::add-line:vertical {\n"
"background: rgb(0,115,170);\n"
"height: 20px;\n"
"subcontrol-position: bottom;\n"
"subcontrol-origin: margin;\n"
"}\n"
"/* SUBPAGES - ADDPAGE */\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"background: none;\n"
"}\n"
"/* ---------------------------------- Q TOOL BAR -------------------------------------------------------- */\n"
"/* TOOLBAR REGION */\n"
"QToolBar {\n"
"background: rgb(35,40,45);\n"
"spacing: 20;\n"
"\n"
"}\n"
"/* SEPARATOR */\n"
"QToolBar:separator\n"
"{\n"
"background: rgb(80, 80, 80);\n"
"height: 2;\n"
"}\n"
"/* QToolBar QToolButton { \n"
"    width: 100px;\n"
"} */\n"
"/* -----------------------------------------------Q TOOL BUTTON------------------------------------------- */\n"
"/* BUTTON */\n"
"QToolButton\n"
"{\n"
"color: rgb(255, 255, 255);\n"
"background:rgb(35,40,45);\n"
"}\n"
"\n"
"QToolButton:hover,QToolButton:pressed\n"
"{\n"
"background-color: rgb(64, 73, 82);\n"
"}\n"
"\n"
"QMessageBox QLabel\n"
"{\n"
"color: red;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"    padding: 4px;\n"
"}")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.North)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setTabBarAutoHide(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setObjectName("tab_1")
        self.Save_Pass_CheckBox = QtWidgets.QCheckBox(self.tab_1)
        self.Save_Pass_CheckBox.setGeometry(QtCore.QRect(1120, 520, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Save_Pass_CheckBox.setFont(font)
        self.Save_Pass_CheckBox.setObjectName("Save_Pass_CheckBox")
        self.Username = QtWidgets.QLineEdit(self.tab_1)
        self.Username.setGeometry(QtCore.QRect(660, 390, 611, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Username.setFont(font)
        self.Username.setObjectName("Username")
        self.label_28 = QtWidgets.QLabel(self.tab_1)
        self.label_28.setGeometry(QtCore.QRect(850, 130, 221, 201))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_28.setFont(font)
        self.label_28.setText("")
        self.label_28.setPixmap(QtGui.QPixmap(":/ico/login3.png"))
        self.label_28.setObjectName("label_28")
        self.Login_Button = QtWidgets.QPushButton(self.tab_1)
        self.Login_Button.setGeometry(QtCore.QRect(660, 570, 611, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Login_Button.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/ico/logout.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Login_Button.setIcon(icon1)
        self.Login_Button.setIconSize(QtCore.QSize(40, 40))
        self.Login_Button.setObjectName("Login_Button")
        self.label_27 = QtWidgets.QLabel(self.tab_1)
        self.label_27.setGeometry(QtCore.QRect(540, 460, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.Password = QtWidgets.QLineEdit(self.tab_1)
        self.Password.setGeometry(QtCore.QRect(660, 460, 611, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Password.setFont(font)
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.label_26 = QtWidgets.QLabel(self.tab_1)
        self.label_26.setGeometry(QtCore.QRect(540, 390, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.Verion = QtWidgets.QLabel(self.tab_1)
        self.Verion.setGeometry(QtCore.QRect(950, 730, 41, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Verion.setFont(font)
        self.Verion.setObjectName("Verion")
        self.Coder_Name = QtWidgets.QLabel(self.tab_1)
        self.Coder_Name.setGeometry(QtCore.QRect(910, 670, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Coder_Name.setFont(font)
        self.Coder_Name.setObjectName("Coder_Name")
        self.Telegram_Link = QtWidgets.QLabel(self.tab_1)
        self.Telegram_Link.setGeometry(QtCore.QRect(920, 700, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.Telegram_Link.setFont(font)
        self.Telegram_Link.setOpenExternalLinks(True)
        self.Telegram_Link.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.Telegram_Link.setObjectName("Telegram_Link")
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 20, 1821, 381))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setFlat(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_10.setGeometry(QtCore.QRect(110, 140, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_10.setFont(font)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 200, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_12.setGeometry(QtCore.QRect(110, 200, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_12.setFont(font)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.Search = QtWidgets.QLineEdit(self.groupBox_3)
        self.Search.setGeometry(QtCore.QRect(110, 50, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Search.setFont(font)
        self.Search.setObjectName("Search")
        self.Search_ComboBox = QtWidgets.QComboBox(self.groupBox_3)
        self.Search_ComboBox.setGeometry(QtCore.QRect(1000, 50, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_ComboBox.setFont(font)
        self.Search_ComboBox.setObjectName("Search_ComboBox")
        self.Search_ComboBox.addItem("")
        self.Search_ComboBox.addItem("")
        self.Search_ComboBox.addItem("")
        self.Search_ComboBox.addItem("")
        self.Search_ComboBox.addItem("")
        self.label_13 = QtWidgets.QLabel(self.groupBox_3)
        self.label_13.setGeometry(QtCore.QRect(10, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.groupBox_3)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 260, 831, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_11.setFont(font)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setGeometry(QtCore.QRect(10, 260, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.Delete_Multi_Button = QtWidgets.QPushButton(self.groupBox_3)
        self.Delete_Multi_Button.setGeometry(QtCore.QRect(1560, 120, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Multi_Button.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/ico/remove-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Delete_Multi_Button.setIcon(icon2)
        self.Delete_Multi_Button.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Multi_Button.setObjectName("Delete_Multi_Button")
        self.lineEdit_10.raise_()
        self.label_11.raise_()
        self.label_12.raise_()
        self.lineEdit_12.raise_()
        self.Search.raise_()
        self.label_13.raise_()
        self.lineEdit_11.raise_()
        self.label_14.raise_()
        self.Search_ComboBox.raise_()
        self.Delete_Multi_Button.raise_()
        self.Update_Button = QtWidgets.QPushButton(self.tab_2)
        self.Update_Button.setGeometry(QtCore.QRect(1600, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Button.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/ico/user_edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Update_Button.setIcon(icon3)
        self.Update_Button.setIconSize(QtCore.QSize(40, 40))
        self.Update_Button.setObjectName("Update_Button")
        self.Delete_Button = QtWidgets.QPushButton(self.tab_2)
        self.Delete_Button.setGeometry(QtCore.QRect(1360, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Button.setFont(font)
        self.Delete_Button.setIcon(icon2)
        self.Delete_Button.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Button.setObjectName("Delete_Button")
        self.Add_Button = QtWidgets.QPushButton(self.tab_2)
        self.Add_Button.setGeometry(QtCore.QRect(1360, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/ico/images-removebg-preview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Add_Button.setIcon(icon4)
        self.Add_Button.setIconSize(QtCore.QSize(40, 40))
        self.Add_Button.setObjectName("Add_Button")
        self.Search_Button = QtWidgets.QPushButton(self.tab_2)
        self.Search_Button.setGeometry(QtCore.QRect(1040, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_Button.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/ico/search-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Search_Button.setIcon(icon5)
        self.Search_Button.setIconSize(QtCore.QSize(35, 35))
        self.Search_Button.setObjectName("Search_Button")
        self.Rest_Button = QtWidgets.QPushButton(self.tab_2)
        self.Rest_Button.setGeometry(QtCore.QRect(1600, 210, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rest_Button.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/ico/reset.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Rest_Button.setIcon(icon6)
        self.Rest_Button.setIconSize(QtCore.QSize(35, 35))
        self.Rest_Button.setObjectName("Rest_Button")
        self.Refresh_Button = QtWidgets.QPushButton(self.tab_2)
        self.Refresh_Button.setGeometry(QtCore.QRect(1360, 210, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Refresh_Button.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/ico/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Refresh_Button.setIcon(icon7)
        self.Refresh_Button.setIconSize(QtCore.QSize(35, 35))
        self.Refresh_Button.setObjectName("Refresh_Button")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(50, 400, 1811, 451))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget.setFont(font)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(12)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(11, item)
        self.groupBox_3.raise_()
        self.Update_Button.raise_()
        self.Delete_Button.raise_()
        self.Add_Button.raise_()
        self.Search_Button.raise_()
        self.Refresh_Button.raise_()
        self.Rest_Button.raise_()
        self.tableWidget.raise_()
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("Convert/pencil.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_2, icon8, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.tab)
        self.tableWidget_2.setGeometry(QtCore.QRect(50, 400, 1811, 461))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(12)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(11, item)
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(40, 20, 1821, 381))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 170, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_14.setGeometry(QtCore.QRect(130, 110, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_14.setFont(font)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_16.setGeometry(QtCore.QRect(130, 170, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_16.setFont(font)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.Search_2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.Search_2.setGeometry(QtCore.QRect(130, 50, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Search_2.setFont(font)
        self.Search_2.setObjectName("Search_2")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.groupBox_4)
        self.lineEdit_19.setGeometry(QtCore.QRect(130, 230, 811, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.lineEdit_19.setFont(font)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(10, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.Search_ComboBox_2 = QtWidgets.QComboBox(self.tab)
        self.Search_ComboBox_2.setGeometry(QtCore.QRect(1040, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_ComboBox_2.setFont(font)
        self.Search_ComboBox_2.setObjectName("Search_ComboBox_2")
        self.Search_ComboBox_2.addItem("")
        self.Search_ComboBox_2.addItem("")
        self.Search_ComboBox_2.addItem("")
        self.Search_ComboBox_2.addItem("")
        self.Search_ComboBox_2.addItem("")
        self.Update_Button_2 = QtWidgets.QPushButton(self.tab)
        self.Update_Button_2.setGeometry(QtCore.QRect(1600, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Button_2.setFont(font)
        self.Update_Button_2.setIcon(icon3)
        self.Update_Button_2.setIconSize(QtCore.QSize(40, 40))
        self.Update_Button_2.setObjectName("Update_Button_2")
        self.Delete_Multi_Button_2 = QtWidgets.QPushButton(self.tab)
        self.Delete_Multi_Button_2.setGeometry(QtCore.QRect(1600, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Multi_Button_2.setFont(font)
        self.Delete_Multi_Button_2.setIcon(icon2)
        self.Delete_Multi_Button_2.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Multi_Button_2.setObjectName("Delete_Multi_Button_2")
        self.Delete_Button_2 = QtWidgets.QPushButton(self.tab)
        self.Delete_Button_2.setGeometry(QtCore.QRect(1360, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Button_2.setFont(font)
        self.Delete_Button_2.setIcon(icon2)
        self.Delete_Button_2.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Button_2.setObjectName("Delete_Button_2")
        self.Search_Button_2 = QtWidgets.QPushButton(self.tab)
        self.Search_Button_2.setGeometry(QtCore.QRect(1040, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_Button_2.setFont(font)
        self.Search_Button_2.setIcon(icon5)
        self.Search_Button_2.setIconSize(QtCore.QSize(35, 35))
        self.Search_Button_2.setObjectName("Search_Button_2")
        self.Add_Button_2 = QtWidgets.QPushButton(self.tab)
        self.Add_Button_2.setGeometry(QtCore.QRect(1360, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Button_2.setFont(font)
        self.Add_Button_2.setIcon(icon4)
        self.Add_Button_2.setIconSize(QtCore.QSize(40, 40))
        self.Add_Button_2.setObjectName("Add_Button_2")
        self.Refresh_Button_2 = QtWidgets.QPushButton(self.tab)
        self.Refresh_Button_2.setGeometry(QtCore.QRect(1360, 210, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Refresh_Button_2.setFont(font)
        self.Refresh_Button_2.setIcon(icon7)
        self.Refresh_Button_2.setIconSize(QtCore.QSize(35, 35))
        self.Refresh_Button_2.setObjectName("Refresh_Button_2")
        self.Rest_Button_2 = QtWidgets.QPushButton(self.tab)
        self.Rest_Button_2.setGeometry(QtCore.QRect(1600, 210, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rest_Button_2.setFont(font)
        self.Rest_Button_2.setIcon(icon6)
        self.Rest_Button_2.setIconSize(QtCore.QSize(35, 35))
        self.Rest_Button_2.setObjectName("Rest_Button_2")
        self.tabWidget.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tableWidget_3 = QtWidgets.QTableWidget(self.tab_3)
        self.tableWidget_3.setGeometry(QtCore.QRect(50, 400, 1811, 461))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_3.setFont(font)
        self.tableWidget_3.setObjectName("tableWidget_3")
        self.tableWidget_3.setColumnCount(13)
        self.tableWidget_3.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_3.setHorizontalHeaderItem(12, item)
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_3)
        self.groupBox_5.setGeometry(QtCore.QRect(40, 20, 1821, 381))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.label_17 = QtWidgets.QLabel(self.groupBox_5)
        self.label_17.setGeometry(QtCore.QRect(10, 170, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.Master = QtWidgets.QLineEdit(self.groupBox_5)
        self.Master.setGeometry(QtCore.QRect(130, 110, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Master.setFont(font)
        self.Master.setObjectName("Master")
        self.label_20 = QtWidgets.QLabel(self.groupBox_5)
        self.label_20.setGeometry(QtCore.QRect(10, 110, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.Client = QtWidgets.QLineEdit(self.groupBox_5)
        self.Client.setGeometry(QtCore.QRect(130, 170, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Client.setFont(font)
        self.Client.setObjectName("Client")
        self.Search_3 = QtWidgets.QLineEdit(self.groupBox_5)
        self.Search_3.setGeometry(QtCore.QRect(130, 50, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Search_3.setFont(font)
        self.Search_3.setObjectName("Search_3")
        self.label_21 = QtWidgets.QLabel(self.groupBox_5)
        self.label_21.setGeometry(QtCore.QRect(10, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.Period = QtWidgets.QLineEdit(self.groupBox_5)
        self.Period.setGeometry(QtCore.QRect(130, 230, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Period.setFont(font)
        self.Period.setObjectName("Period")
        self.label_22 = QtWidgets.QLabel(self.groupBox_5)
        self.label_22.setGeometry(QtCore.QRect(10, 230, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_5)
        self.label_23.setGeometry(QtCore.QRect(10, 280, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.user_id = QtWidgets.QLineEdit(self.groupBox_5)
        self.user_id.setGeometry(QtCore.QRect(130, 280, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.user_id.setFont(font)
        self.user_id.setObjectName("user_id")
        self.Search_Button_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Search_Button_3.setGeometry(QtCore.QRect(1000, 120, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_Button_3.setFont(font)
        self.Search_Button_3.setIcon(icon5)
        self.Search_Button_3.setIconSize(QtCore.QSize(35, 35))
        self.Search_Button_3.setObjectName("Search_Button_3")
        self.Delete_Button_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Delete_Button_3.setGeometry(QtCore.QRect(1320, 120, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Button_3.setFont(font)
        self.Delete_Button_3.setIcon(icon2)
        self.Delete_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Button_3.setObjectName("Delete_Button_3")
        self.Delete_Multi_Button_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Delete_Multi_Button_3.setGeometry(QtCore.QRect(1560, 120, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Multi_Button_3.setFont(font)
        self.Delete_Multi_Button_3.setIcon(icon2)
        self.Delete_Multi_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Multi_Button_3.setObjectName("Delete_Multi_Button_3")
        self.Refresh_Button_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Refresh_Button_3.setGeometry(QtCore.QRect(1320, 190, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Refresh_Button_3.setFont(font)
        self.Refresh_Button_3.setIcon(icon7)
        self.Refresh_Button_3.setIconSize(QtCore.QSize(35, 35))
        self.Refresh_Button_3.setObjectName("Refresh_Button_3")
        self.Update_Button_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Update_Button_3.setGeometry(QtCore.QRect(1560, 50, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Button_3.setFont(font)
        self.Update_Button_3.setIcon(icon3)
        self.Update_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.Update_Button_3.setObjectName("Update_Button_3")
        self.Rest_Button_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Rest_Button_3.setGeometry(QtCore.QRect(1560, 190, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rest_Button_3.setFont(font)
        self.Rest_Button_3.setIcon(icon6)
        self.Rest_Button_3.setIconSize(QtCore.QSize(35, 35))
        self.Rest_Button_3.setObjectName("Rest_Button_3")
        self.Search_ComboBox_3 = QtWidgets.QComboBox(self.groupBox_5)
        self.Search_ComboBox_3.setGeometry(QtCore.QRect(1000, 50, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_ComboBox_3.setFont(font)
        self.Search_ComboBox_3.setObjectName("Search_ComboBox_3")
        self.Search_ComboBox_3.addItem("")
        self.Search_ComboBox_3.addItem("")
        self.Search_ComboBox_3.addItem("")
        self.Search_ComboBox_3.addItem("")
        self.Search_ComboBox_3.addItem("")
        self.Add_Button_3 = QtWidgets.QPushButton(self.groupBox_5)
        self.Add_Button_3.setGeometry(QtCore.QRect(1320, 50, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Button_3.setFont(font)
        self.Add_Button_3.setIcon(icon4)
        self.Add_Button_3.setIconSize(QtCore.QSize(40, 40))
        self.Add_Button_3.setObjectName("Add_Button_3")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tableWidget_4 = QtWidgets.QTableWidget(self.tab_4)
        self.tableWidget_4.setGeometry(QtCore.QRect(50, 400, 1811, 461))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_4.setFont(font)
        self.tableWidget_4.setObjectName("tableWidget_4")
        self.tableWidget_4.setColumnCount(15)
        self.tableWidget_4.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(14, item)
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_6.setGeometry(QtCore.QRect(40, 20, 1821, 381))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_40 = QtWidgets.QLabel(self.groupBox_6)
        self.label_40.setGeometry(QtCore.QRect(10, 220, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.Master_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.Master_4.setGeometry(QtCore.QRect(130, 100, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Master_4.setFont(font)
        self.Master_4.setObjectName("Master_4")
        self.label_41 = QtWidgets.QLabel(self.groupBox_6)
        self.label_41.setGeometry(QtCore.QRect(10, 100, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.Client_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.Client_4.setGeometry(QtCore.QRect(130, 220, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Client_4.setFont(font)
        self.Client_4.setObjectName("Client_4")
        self.Search_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.Search_4.setGeometry(QtCore.QRect(130, 50, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Search_4.setFont(font)
        self.Search_4.setObjectName("Search_4")
        self.label_42 = QtWidgets.QLabel(self.groupBox_6)
        self.label_42.setGeometry(QtCore.QRect(10, 50, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.Period_4 = QtWidgets.QLineEdit(self.groupBox_6)
        self.Period_4.setGeometry(QtCore.QRect(130, 320, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.Period_4.setFont(font)
        self.Period_4.setObjectName("Period_4")
        self.label_43 = QtWidgets.QLabel(self.groupBox_6)
        self.label_43.setGeometry(QtCore.QRect(10, 320, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.groupBox_6)
        self.label_44.setGeometry(QtCore.QRect(10, 270, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.client_user_id_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.client_user_id_7.setGeometry(QtCore.QRect(130, 270, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.client_user_id_7.setFont(font)
        self.client_user_id_7.setObjectName("client_user_id_7")
        self.label_69 = QtWidgets.QLabel(self.groupBox_6)
        self.label_69.setGeometry(QtCore.QRect(10, 160, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.master_user_id_7 = QtWidgets.QLineEdit(self.groupBox_6)
        self.master_user_id_7.setGeometry(QtCore.QRect(130, 160, 801, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.master_user_id_7.setFont(font)
        self.master_user_id_7.setObjectName("master_user_id_7")
        self.Add_Button_4 = QtWidgets.QPushButton(self.tab_4)
        self.Add_Button_4.setGeometry(QtCore.QRect(1360, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Button_4.setFont(font)
        self.Add_Button_4.setIcon(icon4)
        self.Add_Button_4.setIconSize(QtCore.QSize(40, 40))
        self.Add_Button_4.setObjectName("Add_Button_4")
        self.Update_Button_4 = QtWidgets.QPushButton(self.tab_4)
        self.Update_Button_4.setGeometry(QtCore.QRect(1600, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Button_4.setFont(font)
        self.Update_Button_4.setIcon(icon3)
        self.Update_Button_4.setIconSize(QtCore.QSize(40, 40))
        self.Update_Button_4.setObjectName("Update_Button_4")
        self.Search_Button_4 = QtWidgets.QPushButton(self.tab_4)
        self.Search_Button_4.setGeometry(QtCore.QRect(1040, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_Button_4.setFont(font)
        self.Search_Button_4.setIcon(icon5)
        self.Search_Button_4.setIconSize(QtCore.QSize(35, 35))
        self.Search_Button_4.setObjectName("Search_Button_4")
        self.Rest_Button_4 = QtWidgets.QPushButton(self.tab_4)
        self.Rest_Button_4.setGeometry(QtCore.QRect(1600, 210, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Rest_Button_4.setFont(font)
        self.Rest_Button_4.setIcon(icon6)
        self.Rest_Button_4.setIconSize(QtCore.QSize(35, 35))
        self.Rest_Button_4.setObjectName("Rest_Button_4")
        self.Search_ComboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.Search_ComboBox_4.setGeometry(QtCore.QRect(1040, 70, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_ComboBox_4.setFont(font)
        self.Search_ComboBox_4.setObjectName("Search_ComboBox_4")
        self.Search_ComboBox_4.addItem("")
        self.Search_ComboBox_4.addItem("")
        self.Search_ComboBox_4.addItem("")
        self.Search_ComboBox_4.addItem("")
        self.Search_ComboBox_4.addItem("")
        self.Delete_Multi_Button_4 = QtWidgets.QPushButton(self.tab_4)
        self.Delete_Multi_Button_4.setGeometry(QtCore.QRect(1600, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Multi_Button_4.setFont(font)
        self.Delete_Multi_Button_4.setIcon(icon2)
        self.Delete_Multi_Button_4.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Multi_Button_4.setObjectName("Delete_Multi_Button_4")
        self.Delete_Button_4 = QtWidgets.QPushButton(self.tab_4)
        self.Delete_Button_4.setGeometry(QtCore.QRect(1360, 140, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Button_4.setFont(font)
        self.Delete_Button_4.setIcon(icon2)
        self.Delete_Button_4.setIconSize(QtCore.QSize(40, 40))
        self.Delete_Button_4.setObjectName("Delete_Button_4")
        self.Refresh_Button_4 = QtWidgets.QPushButton(self.tab_4)
        self.Refresh_Button_4.setGeometry(QtCore.QRect(1360, 210, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Refresh_Button_4.setFont(font)
        self.Refresh_Button_4.setIcon(icon7)
        self.Refresh_Button_4.setIconSize(QtCore.QSize(35, 35))
        self.Refresh_Button_4.setObjectName("Refresh_Button_4")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.Search_ComboBox_9 = QtWidgets.QComboBox(self.tab_8)
        self.Search_ComboBox_9.setGeometry(QtCore.QRect(590, 110, 621, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Search_ComboBox_9.setFont(font)
        self.Search_ComboBox_9.setObjectName("Search_ComboBox_9")
        self.Search_ComboBox_9.addItem("")
        self.Search_ComboBox_9.addItem("")
        self.label_243 = QtWidgets.QLabel(self.tab_8)
        self.label_243.setGeometry(QtCore.QRect(400, 120, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_243.setFont(font)
        self.label_243.setObjectName("label_243")
        self.Update_Button_9 = QtWidgets.QPushButton(self.tab_8)
        self.Update_Button_9.setGeometry(QtCore.QRect(1290, 110, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Update_Button_9.setFont(font)
        self.Update_Button_9.setIcon(icon3)
        self.Update_Button_9.setIconSize(QtCore.QSize(40, 40))
        self.Update_Button_9.setObjectName("Update_Button_9")
        self.Add_Extra_Days_2 = QtWidgets.QPushButton(self.tab_8)
        self.Add_Extra_Days_2.setGeometry(QtCore.QRect(1300, 260, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Add_Extra_Days_2.setFont(font)
        self.Add_Extra_Days_2.setIcon(icon3)
        self.Add_Extra_Days_2.setIconSize(QtCore.QSize(40, 40))
        self.Add_Extra_Days_2.setObjectName("Add_Extra_Days_2")
        self.label_29 = QtWidgets.QLabel(self.tab_8)
        self.label_29.setGeometry(QtCore.QRect(430, 270, 51, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.Extra_Period = QtWidgets.QLineEdit(self.tab_8)
        self.Extra_Period.setGeometry(QtCore.QRect(600, 270, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.Extra_Period.setFont(font)
        self.Extra_Period.setObjectName("Extra_Period")
        self.Extra_Period_ComboBox = QtWidgets.QComboBox(self.tab_8)
        self.Extra_Period_ComboBox.setGeometry(QtCore.QRect(810, 270, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Extra_Period_ComboBox.setFont(font)
        self.Extra_Period_ComboBox.setObjectName("Extra_Period_ComboBox")
        self.Extra_Period_ComboBox.addItem("")
        self.Extra_Period_ComboBox.addItem("")
        self.Extra_Period_ComboBox.addItem("")
        self.Extra_Period_ComboBox.addItem("")
        self.delete_inactive = QtWidgets.QPushButton(self.tab_8)
        self.delete_inactive.setGeometry(QtCore.QRect(1300, 370, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_inactive.setFont(font)
        self.delete_inactive.setIcon(icon3)
        self.delete_inactive.setIconSize(QtCore.QSize(40, 40))
        self.delete_inactive.setObjectName("delete_inactive")
        self.limit = QtWidgets.QLineEdit(self.tab_8)
        self.limit.setGeometry(QtCore.QRect(600, 380, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.limit.setFont(font)
        self.limit.setObjectName("limit")
        self.Delete_Inactive_ComboBox = QtWidgets.QComboBox(self.tab_8)
        self.Delete_Inactive_ComboBox.setGeometry(QtCore.QRect(810, 380, 401, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Delete_Inactive_ComboBox.setFont(font)
        self.Delete_Inactive_ComboBox.setObjectName("Delete_Inactive_ComboBox")
        self.Delete_Inactive_ComboBox.addItem("")
        self.Delete_Inactive_ComboBox.addItem("")
        self.Delete_Inactive_ComboBox.addItem("")
        self.Delete_Inactive_ComboBox.addItem("")
        self.delete_inactive_users = QtWidgets.QLabel(self.tab_8)
        self.delete_inactive_users.setGeometry(QtCore.QRect(430, 380, 151, 31))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.delete_inactive_users.setFont(font)
        self.delete_inactive_users.setObjectName("delete_inactive_users")
        self.tabWidget.addTab(self.tab_8, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1901, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Dashboard"))
        self.Save_Pass_CheckBox.setText(_translate("MainWindow", "Save Password"))
        self.Username.setPlaceholderText(_translate("MainWindow", "  Enter Your Username"))
        self.Login_Button.setText(_translate("MainWindow", "Login"))
        self.label_27.setText(_translate("MainWindow", "Password"))
        self.Password.setPlaceholderText(_translate("MainWindow", "  Enter Your Password"))
        self.label_26.setText(_translate("MainWindow", "Username"))
        self.Verion.setText(_translate("MainWindow", "V2.0"))
        self.Coder_Name.setText(_translate("MainWindow", "Cᴏᴅᴇʀ : Gʟɪᴛᴄʜ"))
        self.Telegram_Link.setText(_translate("MainWindow", "<a href=\"https://t.me/M0hammedSaeed\" target=\"_blank\" style=\"text-decoration: none;color: #218cf0;\" >My Telegram</a>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), _translate("MainWindow", "   Login   "))
        self.groupBox_3.setTitle(_translate("MainWindow", "User Subscriptions - Add, Edit Or Delete User"))
        self.label_11.setText(_translate("MainWindow", "Source Account Email"))
        self.label_12.setText(_translate("MainWindow", "Target Account Email"))
        self.Search_ComboBox.setItemText(0, _translate("MainWindow", "---------------------------------------"))
        self.Search_ComboBox.setItemText(1, _translate("MainWindow", "ID"))
        self.Search_ComboBox.setItemText(2, _translate("MainWindow", "Source Account"))
        self.Search_ComboBox.setItemText(3, _translate("MainWindow", "Target Account"))
        self.Search_ComboBox.setItemText(4, _translate("MainWindow", "Source & Target Account"))
        self.label_13.setText(_translate("MainWindow", "Search"))
        self.label_14.setText(_translate("MainWindow", "Period"))
        self.Delete_Multi_Button.setText(_translate("MainWindow", "Delete Multi"))
        self.Update_Button.setText(_translate("MainWindow", "Update"))
        self.Delete_Button.setText(_translate("MainWindow", "Delete"))
        self.Add_Button.setText(_translate("MainWindow", "Add"))
        self.Search_Button.setText(_translate("MainWindow", "Search"))
        self.Rest_Button.setText(_translate("MainWindow", "Reset"))
        self.Refresh_Button.setText(_translate("MainWindow", "Refresh"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source Account Email"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Target Account Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "To"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Update Date"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Last Login"))
        item = self.tableWidget.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Added By"))
        item = self.tableWidget.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Updated By"))
        item = self.tableWidget.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Account Balance"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "   User Subscriptions   "))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source Account Email"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Target Account Email"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "To"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Update Date"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Last Login"))
        item = self.tableWidget_2.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Added By"))
        item = self.tableWidget_2.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Updated By"))
        item = self.tableWidget_2.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Account Balance"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Account Migrations - Add, Edit Or Delete User"))
        self.label_15.setText(_translate("MainWindow", "Target Account Email"))
        self.label_16.setText(_translate("MainWindow", "Source Account Email"))
        self.label_18.setText(_translate("MainWindow", "Search"))
        self.label_19.setText(_translate("MainWindow", "Period"))
        self.Search_ComboBox_2.setItemText(0, _translate("MainWindow", "---------------------------------------"))
        self.Search_ComboBox_2.setItemText(1, _translate("MainWindow", "ID"))
        self.Search_ComboBox_2.setItemText(2, _translate("MainWindow", "Source Account"))
        self.Search_ComboBox_2.setItemText(3, _translate("MainWindow", "Target Account"))
        self.Search_ComboBox_2.setItemText(4, _translate("MainWindow", "Source & Target Account"))
        self.Update_Button_2.setText(_translate("MainWindow", "Update"))
        self.Delete_Multi_Button_2.setText(_translate("MainWindow", "Delete Multi"))
        self.Delete_Button_2.setText(_translate("MainWindow", "Delete"))
        self.Search_Button_2.setText(_translate("MainWindow", "Search"))
        self.Add_Button_2.setText(_translate("MainWindow", "Add"))
        self.Refresh_Button_2.setText(_translate("MainWindow", "Refresh"))
        self.Rest_Button_2.setText(_translate("MainWindow", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "   Account Migrations   "))
        item = self.tableWidget_3.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_3.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source Account Email"))
        item = self.tableWidget_3.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Target Account Email"))
        item = self.tableWidget_3.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget_3.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Account User ID"))
        item = self.tableWidget_3.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_3.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "To"))
        item = self.tableWidget_3.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_3.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Update Date"))
        item = self.tableWidget_3.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Last Login"))
        item = self.tableWidget_3.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Added By"))
        item = self.tableWidget_3.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Updated By"))
        item = self.tableWidget_3.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Account Balance"))
        self.groupBox_5.setTitle(_translate("MainWindow", "Subscription Mappings - Add, Edit Or Delete User"))
        self.label_17.setText(_translate("MainWindow", "Target Account Email"))
        self.label_20.setText(_translate("MainWindow", "Source Account Email"))
        self.label_21.setText(_translate("MainWindow", "Search"))
        self.label_22.setText(_translate("MainWindow", "Period"))
        self.label_23.setText(_translate("MainWindow", "User ID"))
        self.Search_Button_3.setText(_translate("MainWindow", "Search"))
        self.Delete_Button_3.setText(_translate("MainWindow", "Delete"))
        self.Delete_Multi_Button_3.setText(_translate("MainWindow", "Delete Multi"))
        self.Refresh_Button_3.setText(_translate("MainWindow", "Refresh"))
        self.Update_Button_3.setText(_translate("MainWindow", "Update"))
        self.Rest_Button_3.setText(_translate("MainWindow", "Reset"))
        self.Search_ComboBox_3.setItemText(0, _translate("MainWindow", "---------------------------------------"))
        self.Search_ComboBox_3.setItemText(1, _translate("MainWindow", "ID"))
        self.Search_ComboBox_3.setItemText(2, _translate("MainWindow", "Source Account"))
        self.Search_ComboBox_3.setItemText(3, _translate("MainWindow", "Target Account"))
        self.Search_ComboBox_3.setItemText(4, _translate("MainWindow", "Source & Target Account"))
        self.Add_Button_3.setText(_translate("MainWindow", "Add"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "   Subscription Mappings   "))
        item = self.tableWidget_4.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.tableWidget_4.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Source Account Email"))
        item = self.tableWidget_4.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Source Account User ID"))
        item = self.tableWidget_4.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Target Account Email"))
        item = self.tableWidget_4.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Target Account User ID"))
        item = self.tableWidget_4.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Period"))
        item = self.tableWidget_4.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "From"))
        item = self.tableWidget_4.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "To"))
        item = self.tableWidget_4.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Date"))
        item = self.tableWidget_4.horizontalHeaderItem(9)
        item.setText(_translate("MainWindow", "Update Date"))
        item = self.tableWidget_4.horizontalHeaderItem(10)
        item.setText(_translate("MainWindow", "Last Login"))
        item = self.tableWidget_4.horizontalHeaderItem(11)
        item.setText(_translate("MainWindow", "Added By"))
        item = self.tableWidget_4.horizontalHeaderItem(12)
        item.setText(_translate("MainWindow", "Updated By"))
        item = self.tableWidget_4.horizontalHeaderItem(13)
        item.setText(_translate("MainWindow", "Source Account Balance"))
        item = self.tableWidget_4.horizontalHeaderItem(14)
        item.setText(_translate("MainWindow", "Target Account Balance"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Dual Subscription Mappings - Add, Edit Or Delete User"))
        self.label_40.setText(_translate("MainWindow", "Target Account Email"))
        self.label_41.setText(_translate("MainWindow", "Source Account Email"))
        self.label_42.setText(_translate("MainWindow", "Search"))
        self.label_43.setText(_translate("MainWindow", "Period"))
        self.label_44.setText(_translate("MainWindow", "User ID"))
        self.label_69.setText(_translate("MainWindow", "User ID"))
        self.Add_Button_4.setText(_translate("MainWindow", "Add"))
        self.Update_Button_4.setText(_translate("MainWindow", "Update"))
        self.Search_Button_4.setText(_translate("MainWindow", "Search"))
        self.Rest_Button_4.setText(_translate("MainWindow", "Reset"))
        self.Search_ComboBox_4.setItemText(0, _translate("MainWindow", "---------------------------------------"))
        self.Search_ComboBox_4.setItemText(1, _translate("MainWindow", "ID"))
        self.Search_ComboBox_4.setItemText(2, _translate("MainWindow", "Source Account"))
        self.Search_ComboBox_4.setItemText(3, _translate("MainWindow", "Target Account"))
        self.Search_ComboBox_4.setItemText(4, _translate("MainWindow", "Source & Target Account"))
        self.Delete_Multi_Button_4.setText(_translate("MainWindow", "Delete Multi"))
        self.Delete_Button_4.setText(_translate("MainWindow", "Delete"))
        self.Refresh_Button_4.setText(_translate("MainWindow", "Refresh"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "   Dual Subscription Mappings   "))
        self.Search_ComboBox_9.setItemText(0, _translate("MainWindow", "Light Mode"))
        self.Search_ComboBox_9.setItemText(0, _translate("MainWindow", "Light Mode"))
        self.Search_ComboBox_9.setItemText(1, _translate("MainWindow", "Dark Mode"))
        self.label_243.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">App Theme</p></body></html>"))
        self.Update_Button_9.setText(_translate("MainWindow", "Update"))
        self.Add_Extra_Days_2.setText(_translate("MainWindow", "Add Days Multi"))
        self.label_29.setText(_translate("MainWindow", "Period"))
        self.Extra_Period.setPlaceholderText(_translate("MainWindow", "Enter The Period"))
        self.Extra_Period_ComboBox.setItemText(0, _translate("MainWindow", "user_subscriptions"))
        self.Extra_Period_ComboBox.setItemText(1, _translate("MainWindow", "account_migrations"))
        self.Extra_Period_ComboBox.setItemText(2, _translate("MainWindow", "subscription_mappings"))
        self.Extra_Period_ComboBox.setItemText(3, _translate("MainWindow", "dual_subscription_mappings"))
        self.delete_inactive.setText(_translate("MainWindow", "Delete Inactive Users"))
        self.limit.setPlaceholderText(_translate("MainWindow", "Enter The Limt for deleted users"))
        self.Delete_Inactive_ComboBox.setItemText(0, _translate("MainWindow", "user_subscriptions"))
        self.Delete_Inactive_ComboBox.setItemText(1, _translate("MainWindow", "account_migrations"))
        self.Delete_Inactive_ComboBox.setItemText(2, _translate("MainWindow", "subscription_mappings"))
        self.Delete_Inactive_ComboBox.setItemText(3, _translate("MainWindow", "dual_subscription_mappings"))
        self.delete_inactive_users.setText(_translate("MainWindow", "Delete Inactive Users"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), _translate("MainWindow", "   Settings   "))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
